### PR TITLE
add support for Jetty94

### PR DESCRIPTION
**Pull request by ffoysal**

### CODE REVIEW

**Comment by xzer** [comment]
thanks for your PR.

I tried to compile your sources, and I got the following error:

> [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project runjettyrun.jetty94: Compilation failure: Compilation failure:
> [ERROR]..\run-jetty-run\Jetty94Support\plugin-jetty94\bootstrap\runjettyrun\annotation\RJRAnnotationConfiguration.java:[15]
> [ERROR]         import org.eclipse.jetty.annotations.ClassNameResolver;
> [ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [ERROR] The import org.eclipse.jetty.annotations.ClassNameResolver cannot be resolved
> [ERROR] ...\run-jetty-run\Jetty94Support\plugin-jetty94\bootstrap\runjettyrun\annotation\RJRAnnotationConfiguration.java:[85]
> [ERROR]         ParserTask task = new ParserTask(parser, handlers, dir, _webAppClassNameResolver);

**Comment by ffoysal** [comment]
run_jetty94
I thought in eclipse workspace the compilation error will be shown. I will look into.
Thanks for the feedback

**Comment by xzer** [comment]
perhaps there are something out of synchronization between eclipse and tycho. you probably need to confirm it by "mvn package".

**Comment by ffoysal** [comment]
selection_001
had to remove ClassNameResolver and _webAppClassNameResolver as they don't exist in jetty-annotations-9.4.6.v20170531.jar
Hope it will compile now.

**Comment by xzer** [comment]
I have merge it and uploaded the new plugin build to update site. No version change, since the current new est version is declared as nightly built, I just updated the package.

**Pull request merged**
